### PR TITLE
Label 80 OFFRP

### PR DESCRIPTION
**Pull request by period**
Have made a start on this, but not too sure what to do with the formatted fields for the other info in the message given there seems to be some variation, in particular with the handling of FOB (see comments). Hoping someone else can help out :-)

### CODE REVIEW

**Comment by andermatt64** [comment]
Personally, I think it would definitely be useful to capture the numerical data and store it in the schematized output. We don't know the units of measure now but can possibly deduce it later with future data enrichment (e.g. because we know the plane that emitted this message was a A320 and N nautical miles from destination airport, this figure is most likely in liters because other flights landing at the destination airport around this position have had similar quantities of fuel).

**Comment by kevinelliott** [comment]
> Have made a start on this, but not too sure what to do with the formatted fields for the other info in the message given there seems to be some variation, in particular with the handling of FOB (see comments). Hoping someone else can help out :-)

Nice first pass. Thank you!

> Personally, I think it would definitely be useful to capture the numerical data and store it in the schematized output. We don't know the units of measure now but can possibly deduce it later with future data enrichment (e.g. because we know the plane that emitted this message was a A320 and N nautical miles from destination airport, this figure is most likely in liters because other flights landing at the destination airport around this position have had similar quantities of fuel).

Agreed here with @andermatt64 's comments.

**Comment by kevinelliott** [comment]
Hey @period just checking in to see if you might be open to finishing this one up?

**Comment by kevinelliott** [comment]
@period Thought I'd ping you on this again. Any interest? If I had time (I'm working on too many things across the projects) I'd finish it up, but maybe you can tackle.

**Comment by kevinelliott** [comment]
@period Some of this work that @andermatt64 mentioned has been done already by @makrsmark recently, so you should be able to piggy back on what he's done. Maybe he has the time to adjust this for that.

**Comment by kevinelliott** [comment]
I'm going to close this for now. Please do reopen it if you would like to see it merged.

**Pull request closed without merging**
