### PR TITLE
Fixing Label 44 decoding

### PR DESCRIPTION
**Pull request by makrsmark**
* fix position conversion
* convert HHMMSS now supports minute resolution (and updated others)

### CODE REVIEW

**Comment by makrsmark** [comment]
Sorry, this got a little big - I can split out the month and day changes , if you want

**Comment by makrsmark** [comment]
> Sorry, this got a little big - I can split out the month and day changes as one PR, and the HHMMSS changes as another, if you want

Broken up. this now depends on https://github.com/airframesio/acars-decoder-typescript/pull/190 to pass tests

**Comment by kevinelliott** [comment]
The other two are approved.

**Review by kevinelliott — APPROVED** [review]
LGTM. It was nice to see the extraction.

**Pull request merged**
